// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCREa2r8U6qn9UCaZ9_lHPz3rgu3Crv_7Q',
    appId: '1:698734756733:web:f6470436729336ceaf0214',
    messagingSenderId: '698734756733',
    projectId: 'cuidapet-leia',
    authDomain: 'cuidapet-leia.firebaseapp.com',
    storageBucket: 'cuidapet-leia.appspot.com',
    measurementId: 'G-BZX03X0GPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE_43sazQc0589ed36-C5sumCJPdbh_s8',
    appId: '1:698734756733:android:a04f40421e7a71c1af0214',
    messagingSenderId: '698734756733',
    projectId: 'cuidapet-leia',
    storageBucket: 'cuidapet-leia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaSDUq_GHF_JijdXSmLSuwmVgku2qicAk',
    appId: '1:698734756733:ios:73dc7b57eb61f617af0214',
    messagingSenderId: '698734756733',
    projectId: 'cuidapet-leia',
    storageBucket: 'cuidapet-leia.appspot.com',
    iosBundleId: 'br.com.clinformatica.cuidapetLeia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaSDUq_GHF_JijdXSmLSuwmVgku2qicAk',
    appId: '1:698734756733:ios:8ef68a776fde2a12af0214',
    messagingSenderId: '698734756733',
    projectId: 'cuidapet-leia',
    storageBucket: 'cuidapet-leia.appspot.com',
    iosBundleId: 'br.com.clinformatica.cuidapetLeia.RunnerTests',
  );
}
